import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, EmailStr
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="HR Insights API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)


# ── Request model ─────────────────────────────────────────────────────────────

class ReportRequest(BaseModel):
    recipients: list[EmailStr]
    subject: str = "HR Case Insights Report"
    filename: str = "report"
    summary_html: str        # rendered HTML summary block from the frontend
    csv_data: str | None = None  # optional CSV string to attach


# ── Email helper ──────────────────────────────────────────────────────────────

def build_email_html(summary_html: str, filename: str) -> str:
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f3; margin: 0; padding: 0; }}
  .wrapper {{ max-width: 680px; margin: 32px auto; background: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid rgba(0,0,0,0.08); }}
  .header {{ background: #1a1a18; padding: 28px 32px; }}
  .header h1 {{ color: #f0f0ee; font-size: 20px; font-weight: 600; margin: 0 0 4px; }}
  .header p {{ color: #9e9e9a; font-size: 13px; margin: 0; }}
  .body {{ padding: 28px 32px; }}
  .meta {{ font-size: 12px; color: #9e9e9a; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid rgba(0,0,0,0.07); }}
  .metrics {{ display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 24px; }}
  .footer {{ background: #f5f5f3; padding: 18px 32px; font-size: 12px; color: #9e9e9a; border-top: 1px solid rgba(0,0,0,0.07); }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>HR Case Insights</h1>
    <p>Automated report from ServiceNow export</p>
  </div>
  <div class="body">
    <p class="meta">Generated from <strong>{filename}</strong> &nbsp;·&nbsp; {now}</p>
    {summary_html}
  </div>
  <div class="footer">
    This report was generated by the HR Case Insights tool. Data processed entirely server-side and not stored.
  </div>
</div>
</body>
</html>
"""


def send_email(recipients: list[str], subject: str, html_body: str,
               csv_data: str | None, filename: str):
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "465"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    sender    = os.getenv("SENDER_EMAIL", smtp_user)

    if not smtp_user or not smtp_pass:
        raise ValueError("SMTP_USER and SMTP_PASS must be set in .env")

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = f"HR Insights <{sender}>"
    msg["To"]      = ", ".join(recipients)

    # HTML body
    msg.attach(MIMEText(html_body, "html"))

    # Optional CSV attachment
    if csv_data:
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(csv_data.encode("utf-8"))
        encoders.encode_base64(attachment)
        safe_name = filename.replace(" ", "_").replace("/", "-")
        attachment.add_header("Content-Disposition", "attachment",
                               filename=f"{safe_name}_report.csv")
        msg.attach(attachment)

    context = ssl.create_default_context()
    # Common SMTP behavior:
    # - 465 uses implicit TLS (SMTP_SSL)
    # - 587/25 usually require STARTTLS upgrade after connect
    if smtp_port == 465:
        with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(sender, recipients, msg.as_string())
    else:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=20) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(sender, recipients, msg.as_string())


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return FileResponse("static/index.html")


@app.post("/send-report")
def send_report(req: ReportRequest):
    if not req.recipients:
        raise HTTPException(status_code=400, detail="No recipients provided.")

    try:
        html_body = build_email_html(req.summary_html, req.filename)
        send_email(
            recipients=req.recipients,
            subject=req.subject,
            html_body=html_body,
            csv_data=req.csv_data,
            filename=req.filename,
        )
        return {"ok": True, "sent_to": req.recipients}
    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except smtplib.SMTPAuthenticationError:
        raise HTTPException(status_code=401, detail="SMTP authentication failed. Check SMTP_USER and SMTP_PASS in .env")
    except smtplib.SMTPException as e:
        raise HTTPException(
            status_code=500,
            detail=(
                f"SMTP error: {str(e)}. Check SMTP_HOST/SMTP_PORT and verify TLS mode "
                "(465 = SSL, 587 = STARTTLS)."
            ),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Unexpected error: {str(e)}")


@app.get("/health")
def health():
    return {"status": "ok", "smtp_configured": bool(os.getenv("SMTP_USER"))}
